# Generated by Django 6.0.1 on 2026-01-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=120)),
                ('family_email', models.EmailField(max_length=254)),
                ('family_city', models.CharField(blank=True, max_length=80)),
                ('family_zipcode', models.CharField(blank=True, max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='providers.professionalprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
